### ISSUE TITLE
Error on PaperMC 1.20.4

### ISSUE THREAD

**Issue by hero23550** [PeriodicSeizures/CRUtils#2]
I receive this [error](https://mclo.gs/gBxTGqL) when I run the command "/lootcrates editor"
 Server Software & version:- PaperMC 1.20.4
CRUtils 1.1.3
Lootcrates 3.4.9
NBT API 2.12.3

**Comment by crazicrafter1** [comment]
Hey, thanks for the heads-up, I appreciate it.

I've updated the required AnvilGUI version and ran a small test, so far it works. If there's more problems just post them here.

**Comment by hero23550** [comment]
Seems to be working fine now, found no errors

**Comment by hero23550** [comment]
resolved
